"""
Blender Bridge for Cybervillage Digital Twin
Executes Blender Python scripts in headless mode and interfaces with AI Director for 3D model generation.
"""
import os
import subprocess
import tempfile
from typing import Optional, Dict, Any

ENGINE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(ENGINE_DIR, ".."))
LOCAL_BLENDER_PATH = os.path.join(ENGINE_DIR, "blender_bin", "blender")
MODELS_DIR = os.path.join(PROJECT_ROOT, "public", "models")

WINDOWS_BLENDER_PATHS = [
    "/mnt/d/Blender/blender.exe",
    "/mnt/c/Program Files/Blender Foundation/Blender 5.2/blender.exe",
    "/mnt/c/Program Files/Blender Foundation/Blender/blender.exe"
]

def get_blender_binary() -> Optional[str]:
    """Finds the blender executable (Windows Blender 5.2 via WSL first, then local binary, then system path)."""
    for win_path in WINDOWS_BLENDER_PATHS:
        if os.path.exists(win_path) and os.access(win_path, os.X_OK):
            return win_path

    if os.path.exists(LOCAL_BLENDER_PATH) and os.access(LOCAL_BLENDER_PATH, os.X_OK):
        return LOCAL_BLENDER_PATH
    
    # Try system blender
    try:
        res = subprocess.run(["which", "blender"], capture_output=True, text=True)
        if res.returncode == 0 and res.stdout.strip():
            return res.stdout.strip()
    except Exception:
        pass
    return None

def run_blender_script(script_path: str, extra_args: list = None) -> Dict[str, Any]:
    """Runs a Python script inside Blender in headless/background mode."""
    blender_bin = get_blender_binary()
    if not blender_bin:
        return {
            "success": False,
            "error": "Blender binary not found. Please install or wait for download to finish."
        }

    rel_script = os.path.relpath(script_path, PROJECT_ROOT) if os.path.isabs(script_path) else script_path
    cmd = [blender_bin, "-b", "--python", rel_script]
    if extra_args:
        cmd.extend(["--"] + extra_args)

    env = os.environ.copy()
    lib_path = os.path.join(ENGINE_DIR, "blender_bin", "lib")
    if os.path.exists(lib_path):
        env["LD_LIBRARY_PATH"] = f"{lib_path}:{env.get('LD_LIBRARY_PATH', '')}"

    try:
        print(f"[Blender Bridge] Running command: {' '.join(cmd)}")
        result = subprocess.run(
            cmd,
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=400,
            env=env
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "exit_code": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "Blender process timed out (400s limit)"}
    except Exception as e:
        return {"success": False, "error": str(e)}

def build_all_masterplan_assets() -> Dict[str, Any]:
    """Executes the master Blender export script."""
    export_script = os.path.join(PROJECT_ROOT, "scripts", "blender", "export_all_models.py")
    if not os.path.exists(export_script):
        return {"success": False, "error": f"Export script not found: {export_script}"}
    return run_blender_script(export_script)

def execute_custom_bpy_code(python_code: str, output_glb_name: str = "custom_asset.glb") -> Dict[str, Any]:
    """Executes raw bpy Python code generated by AI to produce a GLB asset."""
    output_path = os.path.join(MODELS_DIR, output_glb_name)
    
    # Wrapper script that executes code and exports GLB
    wrapper_code = f"""
import bpy
import math

bpy.ops.wm.read_factory_settings(use_empty=True)
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)

# User / AI Code:
{python_code}

# Export GLB:
bpy.ops.export_scene.gltf(
    filepath="{output_path}",
    export_format='GLB',
    export_apply=True,
    export_materials='EXPORT'
)
print("[Blender AI] Successfully exported to {output_path}")
"""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(wrapper_code)
        temp_script = f.name

    try:
        res = run_blender_script(temp_script)
        res["glb_path"] = f"/models/{output_glb_name}"
        return res
    finally:
        if os.path.exists(temp_script):
            os.remove(temp_script)
